# Generated by Django 2.1 on 2018-08-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Formule'},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'verbose_name': 'Permis', 'verbose_name_plural': 'Permis'},
        ),
        migrations.AddField(
            model_name='composition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licence.Licence', verbose_name='Permis associé'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la formule'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du permis'),
        ),
    ]
