# Generated by Django 2.1 on 2018-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='response',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
