# Generated by Django 2.1 on 2018-08-20 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20180820_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='response',
            field=models.BooleanField(default=0, verbose_name='Bonne réponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='media_url',
            field=models.CharField(max_length=200, verbose_name='URL du média'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=500, verbose_name='Question'),
        ),
    ]
